- name: Copy Mongodb Repo File
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-org -y
    state: latest

- name: Update mongodb listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Mongodb service
  ansible.builtin.systemd:
    state: restarted
    name: mongod
    enabled: true