- name: configuring nodeJS repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: install nodeJs
  ansible.builtin.yum:
    name: nodeJs
    state: installed

- name: App pre-reqisities
  ansible.builtin.import_tasks:
    file: app_presetup.yml

- name: Load nodejs dependiencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: SystemD setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml




#app_presetup

#echo -e "${color} Install NodeJS Dependiencies ${nocolor}"

#npm install &>>$log_file

#stat_check $ ?

#systemd_setup