#echo -e "${color} Setup systemD service ${nocolor}"
#cp /home/centos/roboshop-shell/$component.service /etc/systemd/system/$component.service &>>$log_file

#stat_check $?
#echo -e "${color} Start $component Service${nocolor}"
#systemctl daemon-reload &>>$log_file
#systemctl enable $component &>>$log_file
#systemctl restart $component &>>$log_file

#stat_check $?


- name: Copy systemd file
  ansible.builtin.copy:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: start {{ component }} service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: yes
    daemon-reload: yes